language: node_js
node_js:
  - 14
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - abcdkh1209@icloud.com
cache:
  directories:
    - node_modules
script:
  - yarn test
  - yarn build
before_deploy:
  - mkdir -p before-deploy
  - cp -r build/* before-deploy
  - cp appspec.yml before-deploy
  - cd before-deploy && zip -r before-deploy *
  - cd ../ && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/pocket-frontend.zip
deploy:
  - provider: s3
    skip_cleanup: true
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: clroot-pocket-frontend-deploy
    region: ap-northeast-2
    acl: private
    local_dir: deploy
    on:
      repo: clroot/pocket-frontend
      branch: master
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: clroot-pocket-frontend-deploy
    key: pocket-frontend.zip
    bundle_type: zip
    application: pocket-frontend
    deployment_group: pocket-frontend-deploy
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      repo: clroot/pocket-frontend
      branch: master
