version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app/pocket/frontend/
    overwrite: yes

permissions:
  - object: /
    pattern: '**'
    owner: ubuntu
    group: ubuntu
hooks:
  ApplicationStart:
    - location: after-deploy.sh
      timeout: 60
      runas: ubuntu
